stages:
- Build
- Test
- Pack
- Publish

variables:
    versioning_params: '$( [[ "${CI_BUILD_REF_NAME^^}" =~ ^MASTER$|RELEASE\/.* ]] && echo "-p:BuildNumber=$CI_PIPELINE_ID" || echo "-p:BuildNumber=$CI_PIPELINE_ID -p:PreReleaseSuffix=$CI_BUILD_REF_SLUG" )'
    full_sign_params: -p:AssemblyOriginatorKeyFile=$signing_key_path -p:DelaySign=false

Build:
    stage: Build
    script: dotnet build -c Release -p:GeneratePackageOnBuild=false $full_sign_params $(eval $versioning_params)
    artifacts:
        paths:
        - "*/bin/Release"
        - "*/obj"
        
Test:
    stage: Test
    script: dotnet test -c Release --no-build
    dependencies:
    - Build

Pack:
    stage: Pack
    script: dotnet pack -c Release --no-build $(eval $versioning_params)
    dependencies:
    - Build
    artifacts:
        paths:
        - "*/bin/Release"

Publish:
    stage: Publish
    script: dotnet nuget push -k $nuget_publish_key -s https://nuget.ksharp.net/v3/index.json NChronicle.Core/bin/Release/NChronicle.Core.*.nupkg
    dependencies:
    - Pack