stages:
- Build
- Publish

Build:
    stage: Build
    script: dotnet build -c Release -p:AssemblyOriginatorKeyFile=$signing_key_path -p:DelaySign=false -p:BuildNumber=$CI_BUILD_ID
    artifacts:
        paths:
        - bin/Release/
    only:
    - $CI_BUILD_REF_NAME =~ /^master$|release\\.*/i

Build:
    stage: Build
    script: dotnet build -c Release -p:AssemblyOriginatorKeyFile=$signing_key_path -p:DelaySign=false -p:BuildNumber=$CI_BUILD_ID -p:PreReleaseSuffix=$CI_BUILD_REF_SLUG
    artifacts:
        paths:
        - bin/Release/
    except:
    - $CI_BUILD_REF_NAME =~ /^master$|release\\.*/i

Publish:
    stage: Publish
    script: dotnet nuget push -k $nuget_publish_key -s https://nuget.ksharp.net/v3/index.json bin/Release/NChronicle.Core.*.nupkg
    dependencies:
    - Build